# -*- coding: utf-8 -*-
"""HPE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnRcwnHLEw68PaBN2rcZlPchCMkFOAMj

# Full Bottom-Up Pose Estimation Pipeline
"""

# prompt: mount google drive

from google.colab import drive
drive.mount('/content/drive')

# prompt: its mounted, and i will be working in this folder: https://drive.google.com/drive/folders/1TvVnJ0w2GTsMLm0lykzSR_LsZJQAYquo?usp=drive_link

import os
os.chdir("/content/drive/MyDrive/HPE")
!pwd
# Now you can work with files in the specified folder.  For example, to list files:
!ls -l

!unzip /content/drive/MyDrive/HPE/Scale-sensitive-Heatmap.zip -d /content/
!unzip /content/drive/MyDrive/HPE/coco_data.zip -d /content/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Scale-sensitive-Heatmap

!pip install -r requirements.txt

!pip install torch torchvision

!sed -i 's/AT_CHECK/TORCH_CHECK/g' /content/Scale-sensitive-Heatmap/lib/models/dcn/src/deform_conv_cuda.cpp

!sed -i 's/AT_CHECK/TORCH_CHECK/g' /content/Scale-sensitive-Heatmap/lib/models/dcn/src/deform_pool_cuda.cpp

!sed -i 's/numpy==1.16.0/numpy/' /content/Scale-sensitive-Heatmap/requirements.txt

!pip install -r /content/Scale-sensitive-Heatmap/requirements.txt

!TORCH_CUDA_ARCH_LIST="8.0;7.5;7.0;6.1;6.0" python setup.py develop

!sed -i "s/self.pretrained_layers\[0\] is '\*'/self.pretrained_layers[0] == '*'/g" /content/Scale-sensitive-Heatmap/lib/models/pose_higher_hrnet.py
!sed -i "s/self.pretrained_layers\[0\] is '\*'/self.pretrained_layers[0] == '*'/g" /content/Scale-sensitive-Heatmap/lib/models/pose_hrnet.py

!sed -i "s/^import models.mpii_pose_hrnet/# import models.mpii_pose_hrnet/" /content/Scale-sensitive-Heatmap/lib/models/__init__.py

!sed -i "s/^from crowdposetools.cocoeval import COCOeval/# from crowdposetools.cocoeval import COCOeval/" /content/Scale-sensitive-Heatmap/lib/dataset/CrowdPoseDataset.py

!sed -i "s/^from crowdposetools.cocoeval import COCOeval/# from crowdposetools.cocoeval import COCOeval/" /content/Scale-sensitive-Heatmap/lib/dataset/CrowdPoseDatasetGetScoreData.py

!sed -i '/class COCOeval_Rescore_Data/,/^$/s/^/# /' /content/Scale-sensitive-Heatmap/lib/dataset/CrowdPoseDatasetGetScoreData.py

!sed -i "s/^from .CrowdPoseDatasetGetScoreData import CrowdPoseDatasetGetScoreData as crowdposescore/# from .CrowdPoseDatasetGetScoreData import CrowdPoseDatasetGetScoreData as crowdposescore/" /content/Scale-sensitive-Heatmap/lib/dataset/build.py

!sed -i "s/^from .mpii import MPIIDataset/# from .mpii import MPIIDataset/" /content/Scale-sensitive-Heatmap/lib/dataset/__init__.py

!mkdir -p /content/Scale-sensitive-Heatmap/output/coco

!sed -i 's/np.int/int/g' /content/Scale-sensitive-Heatmap/lib/models/pose_hrnet.py

import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())

!mkdir -p /content/Scale-sensitive-Heatmap/data/coco/annotations
!cp /content/coco_data/annotations_trainval2017/annotations/person_keypoints_val2017.json /content/Scale-sensitive-Heatmap/data/coco/annotations/

!mkdir -p /content/Scale-sensitive-Heatmap/data/coco/images
!cp /content/coco_data/val2017.zip /content/Scale-sensitive-Heatmap/data/coco/images/val2017.zip

!sed -i 's/USE: True/USE: False/' /content/Scale-sensitive-Heatmap/experiments/coco/w32/coco_hrnetw32_scale-sensitive.yaml

!python tools/valid.py --cfg experiments/coco/w32/coco_hrnetw32_scale-sensitive.yaml TEST.MODEL_FILE model/COCO_HRNetW32_Scale-sensitive.pth