# -*- coding: utf-8 -*-
"""HPE-DEKR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146M4as7QD71_Q234bqQNiet9hVyxJD4t
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/HRNet/DEKR.git
# %cd DEKR

!pip install -r requirements.txt
!pip install torch torchvision

!unzip /content/drive/MyDrive/HPE/coco_data.zip -d /content/
!mkdir -p /content/DEKR/data/coco/images
!mkdir -p /content/DEKR/data/coco/annotations

# Copy validation images and annotation
!cp -r /content/coco_data/val2017 /content/DEKR/data/coco/images/
!cp /content/coco_data/annotations/person_keypoints_val2017.json /content/DEKR/data/coco/annotations/

!unzip "/content/drive/MyDrive/HPE/model (1).zip" -d /content/DEKR/

!ls /content/DEKR/model/pose_coco/

!ls /content/DEKR/tools/

!mkdir -p /content/DEKR/data/coco/images
!cp /content/coco_data/val2017.zip /content/DEKR/data/coco/images/

!sed -i "s/np.float/float/g" /content/DEKR/lib/utils/rescore.py

# Replace all instances of np.float with float in COCODataset.py
!sed -i "s/np.float/float/g" /content/DEKR/lib/dataset/COCODataset.py

!python tools/valid.py \
  --cfg experiments/coco/w32/w32_4x_reg03_bs10_512_adam_lr1e-3_coco_x140.yaml \
  TEST.MODEL_FILE model/pose_coco/pose_dekr_hrnetw32_coco.pth